[project]
name = "balance-bot"
version = "67"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adafruit-circuitpython-mpu6050>=1.3.8",
    "gpiozero>=2.0.1",
    "adafruit-circuitpython-hcsr04>=0.4.25",
]

[project.urls]
Homepage = "https://github.com/msqr1/balance-bot"

[dependency-groups]
dev = [
    "ruff>=0.16.5",
    "circuitpython-stubs>=10.2.1",
    "mypy>=2.3.1",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.mypy]
disable_error_code = ["import-untyped"]
